# Utilisez une image Python légère
FROM python:3.9-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers nécessaires
COPY ./src /app

# Installer les dépendances
RUN pip install --upgrade pip && pip install -r requirements.txt

# Exposer le port de l'API (exemple avec FastAPI)
EXPOSE 8000

# Commande pour lancer l'API
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
